### ISSUE TITLE
underline width

### ISSUE THREAD

**Issue by mucyomiller** [Slowyn/UnderlineTabBarExample#1]
what if we want to make underline not equal to width of text label but it's parent width

**Comment by Slowyn** [comment]
Currently, the width of an underline is equal to a width of the parent. Take a look at the example with custom tabs.

**Comment by mucyomiller** [comment]
![simulator screen shot - iphone 6 - 2018-07-22 at 01 04 55](https://user-images.githubusercontent.com/11447549/43040779-d4727f66-8d4c-11e8-9ad4-e33f95a6fabd.png)

@Slowyn  that what i mean how can we extend that underlineColor("#7B68EE")  of selected Tab to fit all tab width not width of only label text.

**Comment by mucyomiller** [comment]
@Slowyn  i have seen that in library we have a way to control height and  color but i don't see how a can make that underline to fit that size above thanks

**Comment by Slowyn** [comment]
@mucyomiller. Take a look at the example with custom tabs.
![image](https://user-images.githubusercontent.com/7250604/43050317-72a19cf4-8e0f-11e8-8f2d-13ed3eed6241.png)
Just pass your own view to tab bar like I did it here
https://github.com/Slowyn/UnderlineTabBarExample/blob/master/App.js#L136

**Comment by mucyomiller** [comment]
@Slowyn thanks now it's works!
